/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouSonGoRouteImport } from './routes/thank-you-son-go'
import { Route as IndexRouteImport } from './routes/index'

const ThankYouSonGoRoute = ThankYouSonGoRouteImport.update({
  id: '/thank-you-son-go',
  path: '/thank-you-son-go',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thank-you-son-go': typeof ThankYouSonGoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thank-you-son-go': typeof ThankYouSonGoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thank-you-son-go': typeof ThankYouSonGoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/thank-you-son-go'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/thank-you-son-go'
  id: '__root__' | '/' | '/thank-you-son-go'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThankYouSonGoRoute: typeof ThankYouSonGoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you-son-go': {
      id: '/thank-you-son-go'
      path: '/thank-you-son-go'
      fullPath: '/thank-you-son-go'
      preLoaderRoute: typeof ThankYouSonGoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThankYouSonGoRoute: ThankYouSonGoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
